EXE = viewer
LIB = -lGL -lglut -lGLU
OBJS = slVector.o
CXXFLAGS = -Wall -O3

all: $(EXE)

$(EXE) : $(OBJS)
	g++ $(CXXFLAGS) -o $(EXE) $(OBJS) $(LIB)

clean :
	rm -f $(EXE)
	rm -f *~ *.h.gch *#















